_wandb:
    value:
        cli_version: 0.28.2
        e:
            tx272tl1bzek9mxwcaqxopmxebxv2en2:
                args:
                    - --config_path
                    - pi0_omy.yaml
                codePath: 3.train_model.py
                codePathLocal: 3.train_model.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "315926315008"
                        used: "116240384000"
                executable: /home/gege/miniconda3/envs/py310/bin/python
                git:
                    commit: 6dfb6c55f4a4a19f69100f0595a3f2e40909e86e
                    remote: git@github.com:Gege4526/LeRobot-MuJoCo-Pi0.git
                gpu: NVIDIA GeForce RTX 5050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5050 Laptop GPU
                      uuid: GPU-9b08c5e9-a8ca-9da8-9f3e-a0f5f2f7e984
                host: gege-LOQ-17IRX10
                memory:
                    total: "24890200064"
                os: Linux-6.17.0-35-generic-x86_64-with-glibc2.39
                program: /home/gege/LeRobot-MuJoCo-Pi0/3.train_model.py
                python: CPython 3.10.20
                root: ckpt/pi0_omy
                startedAt: "2026-08-26T13:36:08.643417Z"
                writerId: tx272tl1bzek9mxwcaqxopmxebxv2en2
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.20
            "5": 0.28.2
            "10":
                - 21
            "12": 0.28.2
            "13": linux-x86_64
batch_size:
    value: 16
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: omy_pnp_language
        revision: null
        root: ./demo_data_language
        use_imagenet_stats: true
        video_backend: torchcodec
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: -1
job_name:
    value: pi0_omy
log_freq:
    value: 50
num_workers:
    value: 8
optimizer:
    value:
        betas:
            - 0.9
            - 0.95
        eps: 1e-08
        grad_clip_norm: 10
        lr: 2.5e-05
        type: adamw
        weight_decay: 1e-10
output_dir:
    value: ckpt/pi0_omy
policy:
    value:
        adapt_to_pi_aloha: false
        attention_implementation: eager
        chunk_size: 5
        device: cuda
        empty_cameras: 0
        freeze_vision_encoder: true
        max_action_dim: 32
        max_state_dim: 32
        n_action_steps: 5
        n_obs_steps: 1
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        num_steps: 10
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_lr: 2.5e-05
        optimizer_weight_decay: 1e-10
        proj_width: 1024
        resize_imgs_with_padding:
            - 224
            - 224
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        tokenizer_max_length: 48
        train_expert_only: false
        train_state_proj: true
        type: pi0
        use_amp: false
        use_cache: true
        use_delta_joint_actions_aloha: false
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 10000
scheduler:
    value:
        decay_lr: 2.5e-06
        num_decay_steps: 30000
        num_warmup_steps: 1000
        peak_lr: 2.5e-05
        type: cosine_decay_with_warmup
seed:
    value: 42
steps:
    value: 20000
use_policy_training_preset:
    value: true
wandb:
    value:
        disable_artifact: true
        enable: true
        entity: gege074526
        mode: null
        notes: null
        project: pi0
        run_id: null
